#week 13 = 7 generations
#week 15 = 21 generations


#Given establishment at time 0, at what frequency will a mutation be at time t if it confers benefit s in a population of size N 
sel <- function(s, t, N){
    return(exp(s*t)/(exp(s*t) + 2*N*s))
}

#Compute the frequency of mutation in the vRNA of a monkey at a given timepoint
percentageDR <- function(monk, weekval, mutIdent, mutPos){
    relInds <- intersect(
        which(monkid == monk),
        intersect(
            grep("RNA|PLASMA", samp.loc),
            which(weeks == weekval )
        )
    )
    return(length(grep(mutIdent, aa[relInds,mutPos]))/length(relInds))
}

#Convert the week number into "generations after the onset of selective pressure" 
weeksToGens <- function(weekval){
    return((weekval - 12)*7)
}

#Estimate s and plot
estimateS <- function(monk, weekvals, mutIdent, mutPos, plotBool){

    #Get the frequencies at the inputted time periods
    DRfreqs <- c()
    for(weekval in weekvals){
        DRfreqs <- c(DRfreqs, percentageDR(monk, weekval, mutIdent, mutPos))
    }

    #We'll fit to the second timepoint
    tp2 <- DRfreqs[2]
    gen2 <- weeksToGens(weekvals[2])

    svals <- seq(.01, 2, by = .01)
    #What is the first value of s that fits a value for the expected frequency at least as large as the observed frequency
    lik.s <- svals[min(which(sel(svals, gen2, Ne) > tp2))]

    if(plotBool == TRUE){
        plot(weeksToGens(weekvals), DRfreqs, ylim = c(0, 1),
             xlab = "\"Generation\"", ylab = "Frequency of resistance",
             pch = 16, main = paste(monk))
        xvalsPlot <- seq(1, max(weeksToGens(weekvals), 1))
        lines(xvalsPlot, sel(lik.s, xvalsPlot, Ne), col = "red")

        #Plot the value of s approximately 1/2 of the way through the x vals
        plotInd <- round((max(xvalsPlot) - min(weeksToGens(weekvals)))*1/4
                         + min(weeksToGens(weekvals)))
        text(xvalsPlot[plotInd], sel(lik.s, xvalsPlot, Ne)[plotInd] + .05,
             paste("s = ", lik.s, sep = ""), col = "red", pos = 2)
    }

    return(lik.s)
}


#Assuming N = 1.5*10^5
Ne <- 1.5*10^5

layout(matrix(1:3, nrow = 1))
coef.t98 <- estimateS("T98133", c(13, 15, 20), "V|I", 184, TRUE)
coef.039 <- estimateS("A99039", c(13, 16, 20), "V|I", 184, TRUE)
#Note, the A99165 estimate is not included in the main text, because it is unclear whether the mutation sweeps quickly and then decreases in frequency, or whether the sweep was actually this slow. 
coef.165 <- estimateS("A99165", c(13, 15), "N", 103, TRUE)

#Output the results to text
write(paste("Selection coefficients generated by compute-s.r",
            paste("T98133:", coef.t98),
            paste("A99039:", coef.039),
            paste("A99165:", coef.165, "*"),
            paste("*A99165's selection coefficient was not included in the text because of potential non-monotonicity" ),
            sep = "\n"),
      "../out/selection.coefs.txt"
      )

